module.exports.AppBanner = require('./appBanner');
module.exports.AppUpdate = require('./appUpdate');
module.exports.User = require('./users');
module.exports.CareerObjective = require('./careerObjective');
module.exports.City = require('./cities');
module.exports.Candidate = require('./candidate');
module.exports.CandidateDoc=require('./candidatedoc')
module.exports.CandidateRegister=require('./candidateRegsiterModel');
module.exports.CandidateCareer = require('./candidateCareer');
module.exports.CandidateQualification = require('./candidateQualification');
module.exports.CandidateProject = require('./candidateProject');
module.exports.CandidateReference = require('./candidateReference');
module.exports.CorporateRegister=require('./corporateRegisterModel');
module.exports.Country = require('./countries');
module.exports.College = require('./college');
module.exports.CollegeDocuments = require('./collegeDocuments');
module.exports.CollegeTodo = require('./collegeTodo');
module.exports.CollegeSms = require('./collegeSms');
module.exports.CollegeRepresentative = require('./collegeRepresentative');
module.exports.Company = require('./company');
module.exports.CompanyExecutive = require('./companyExecutive');
module.exports.CoverLetter = require('./coverLetter');
module.exports.JobCategory = require('./jobCategory');
module.exports.JobSubCategory = require('./jobSubCategory');
module.exports.Qualification = require('./qualification');
module.exports.MockInterview = require('./mockInterview');
module.exports.MockQuestion = require('./mockQuestion');
module.exports.State = require('./states');
module.exports.Industry = require('./industry');
module.exports.Skill = require('./skills');
module.exports.SkillTest = require('./skillTest');
module.exports.SkillTestQuestion = require('./skillTestQuestion');
module.exports.SubIndustry = require('./subIndustry');
module.exports.SubQualification = require('./subQualification');
module.exports.TestCategory = require('./testCategory');
module.exports.Vacancy = require('./vacancy');
module.exports.VacancyType = require('./vacancyType');
module.exports.University = require('./university');
module.exports.Import = require("./import");
module.exports.HiringStatus = require('./hiringstatus');
module.exports.coinsOffers = require('./coinsOffers')
module.exports.PaymentDetails = require('./paymentDetails')
module.exports.CoinsAlgo = require('./coinsAlgo')
module.exports.AppliedJobs = require('./appliedJobs')
module.exports.template = require('./templates')
module.exports.Consumption = require('./consumption')
module.exports.SmsHistory = require('./smsHistory')
module.exports.CandidateCashBack = require('./candidateCashback')
module.exports.CashBackLogic = require('./cashBackLogic')
module.exports.CashBackRequest = require('./cashbackRequest')
module.exports.CandidateImport = require('./candidateImports')
module.exports.KycDocument = require('./kycDocument')
module.exports.Vouchers=require('./vouchers');
module.exports.VoucherUses=require('./voucherUses');
module.exports.Notification = require('./notification');
module.exports.Referral = require('./referral')
module.exports.VideoData=require('./videoData');
module.exports.Contact=require('./contact')
module.exports.LoanEnquiry = require('./loanEnquiry')
module.exports.Review = require('./reviews');
module.exports.Courses=require('./courses');
module.exports.Post=require('./post');
module.exports.CourseSectors=require('./courseSectors');
module.exports.AppliedCourses = require("./appliedCourses");
module.exports.FAQ = require("./chatfaqs");
// module.exports.Manager = required("");